### PR TITLE
Fix compilation errors

### PR DESCRIPTION
**Pull request by rchastain**
Très beau programme ! Une merveille.

Mon compilateur réclamait le mot-clé **extern** à deux ou trois endroits.

J'ai ouvert une discussion sur [talkchess.com](https://talkchess.com/forum3/viewtopic.php?f=7&t=79341) pour présenter votre programme.

Maintenant, il faut que j'apprenne le protocole ICS. :)

### CODE REVIEW

**Comment by julbra** [comment]
Thanks very much for your interest and kind words. The changes LGTM. As I am not actively maintaining this it will take me a few days to verify.

**Comment by rchastain** [comment]
> Thanks very much for your interest and kind words. The changes LGTM. As I am not actively maintaining this it will take me a few days to verify.

Another thing to do would be to solve the issue that happens when Stockfish is not found. In my private copy, I simply replaced the path to Stockfish, but of course it isn't a solution.
If I understand correctly, Stockfish isn't really needed to use the program, isn't it? So maybe, as a temporary solution, we could simply disable the analyze fonction, when Stockfish is not found? With a warning. What would you think about that?
Because currently the application crashes when it doesn't find Stockfish.
Another possibility would be to include Stockfish binary in the repository.
Regards.
Roland

**Comment by julbra** [comment]
> > Thanks very much for your interest and kind words. The changes LGTM. As I am not actively maintaining this it will take me a few days to verify.
> 
> Another thing to do would be to solve the issue that happens when Stockfish is not found. In my private copy, I simply replaced the path to Stockfish, but of course it isn't a solution. If I understand correctly, Stockfish isn't really needed to use the program, isn't it? So maybe, as a temporary solution, we could simply disable the analyze fonction, when Stockfish is not found? With a warning. What would you think about that? Because currently the application crashes when it doesn't find Stockfish. Another possibility would be to include Stockfish binary in the repository. Regards. Roland

That is correct, Stockfish is not strictly required.
I will look at:
1. adding a command line flag to disable it
2. warn instead of crash if not found

**Comment by julbra** [comment]
@rchastain Thanks. I hadn't built this for a number of years and am slightly horrified at the number of deprecation warnings against modern cairo/gdk.

**Comment by rchastain** [comment]
> 
> That is correct, Stockfish is not strictly required. I will look at:
> 
>     1. adding a command line flag to disable it
> 
>     2. warn instead of crash if not found
> 
> 
> Linked issue here: #23

Good! And why not, too, 1° a command line option to set the Stockfish path; 2° a configuration file to store the options. (My two cents.)

**Pull request merged**
